apiVersion: v1
kind: Pod
metadata:
  name: untrim
  labels:
    run: untrim
spec:
  imagePullSecrets:
    - name: dockerhub-pull
  containers:
  - image: docker.io/valluzzi/untrim:latest
    name: untrim
    command: 
      - untrim
    args:
      - --version
  dnsPolicy: ClusterFirst
  restartPolicy: Never
